locale: "en_EN"
ownerNeedCode: true
itemMaxAmount: 9
lockingLimitEnabled: false
ownerAlerted: true
useEconomy: false
unlockingPaysBack: true
lockables:
- LEGACY_DARK_OAK_DOOR
- LEGACY_SPRUCE_DOOR
- LEGACY_TRAPPED_CHEST
- LEGACY_CHEST
- LEGACY_ACACIA_DOOR
- LEGACY_JUNGLE_DOOR
- LEGACY_BIRCH_DOOR
- LEGACY_WOODEN_DOOR
- LEGACY_IRON_DOOR_BLOCK
- LEGACY_TRAP_DOOR
- LEGACY_FURNACE
- LEGACY_CRAFTING_TABLE
- LEGACY_OAK_FENCE_GATE
- LEGACY_ACACIA_FENCE_GATE
- LEGACY_DARK_OAK_FENCE_GATE
- LEGACY_JUNGLE_FENCE_GATE
- LEGACY_BIRCH_FENCE_GATE
- LEGACY_SPRUCE_FENCE_GATE
inventory:
- DIRT
- COBBLESTONE
- STONE
- SLIME_BLOCK