locale: "en_EN"
ownerNeedCode: true
itemMaxAmount: 9
lockingLimitEnabled: false
ownerAlerted: true
useEconomy: false
unlockingPaysBack: true
lockables:
- OAK_DOOR
- OAK_FENCE_GATE
- OAK_TRAPDOOR
- SPRUCE_DOOR
- SPRUCE_FENCE_GATE
- SPRUCE_TRAPDOOR
- BIRCH_DOOR
- BIRCH_FENCE_GATE
- BIRCH_TRAPDOOR
- JUNGLE_DOOR
- JUNGLE_FENCE_GATE
- JUNGLE_TRAPDOOR
- ACACIA_DOOR
- ACACIA_FENCE_GATE
- ACACIA_TRAPDOOR
- DARK_OAK_DOOR
- DARK_OAK_FENCE_GATE
- DARK_OAK_TRAPDOOR
- CRIMSON_DOOR
- CRIMSON_FENCE_GATE
- CRIMSON_TRAPDOOR
- WARPED_DOOR
- WARPED_FENCE_GATE
- WARPED_TRAPDOOR
- CHEST
- FURNACE
- BARREL
- SMOKER
- SHULKER_BOX
- BLAST_FURNACE
- DISPENSER
- DROPPER
- BREWING_STAND
- HOPPER
- TRAPPED_CHEST
- BLACK_SHULKER_BOX
- WHITE_SHULKER_BOX
- ORANGE_SHULKER_BOX
- MAGENTA_SHULKER_BOX
- LIGHT_BLUE_SHULKER_BOX
- YELLOW_SHULKER_BOX
- LIME_SHULKER_BOX
- PINK_SHULKER_BOX
- GRAY_SHULKER_BOX
- LIGHT_GRAY_SHULKER_BOX
- CYAN_SHULKER_BOX
- PURPLE_SHULKER_BOX
- RED_SHULKER_BOX
- GREEN_SHULKER_BOX
- BROWN_SHULKER_BOX
- BLUE_SHULKER_BOX
inventory:
- DIRT
- COBBLESTONE
- STONE
- SLIME_BLOCK