locale: "en_EN"
ownerNeedCode: true
itemMaxAmount: 9
lockingLimitEnabled: false
ownerAlerted: true
useEconomy: false
unlockingPaysBack: true
lockables:
- DARK_OAK_DOOR
- SPRUCE_DOOR
- TRAPPED_CHEST
- CHEST
- ACACIA_DOOR
- JUNGLE_DOOR
- BIRCH_DOOR
- WOODEN_DOOR
- IRON_DOOR_BLOCK
- TRAP_DOOR
- FURNACE
- WORKBENCH
- FENCE_GATE
- ACACIA_FENCE_GATE
- DARK_OAK_FENCE_GATE
- JUNGLE_FENCE_GATE
- BIRCH_FENCE_GATE
- SPRUCE_FENCE_GATE
inventory:
- DIRT
- COBBLESTONE
- STONE
- SLIME_BLOCK