name: PassLock
author: Kamereon
version : 1.16.2
main: io.github.stealthykamereon.passlock.PassLock
depend: [Vault]
api-version: 1.16

commands:
  passlock:
    description: Basic command for passlock
    usage: /passlock [lock|unlock|help|...]