name: PassLock
author: Kamereon
version : 2.1
main: io.github.stealthykamereon.passlock.PassLock
depend: [Vault]
api-version: 1.16

commands:
  passlock:
    description: Basic command for passlock
    usage: "Usage: /<command> [lock|unlock|help|...]"